### ISSUE TITLE
Hack gryzzly.io

### ISSUE THREAD

**Issue by aitva** [gryzzlybot/www#13]
Les étapes à ne pas oublier avant de livrer le nouveau site :

- [x] créer une page temporaire pour indiquer que le site est indisponible
- [x] mettre en place la page de maintenance
- [x] fixer l'issue #6 -> ajouter un bandeau au dessus des forms pour dire que le message est bien envoyé
- [x] afficher un bandeau si redirection depuis gryzzly.fr vers http://timer.gryzzly.io
- [x] Redirections depuis blog.gryzzly.fr : les url articles envoie sur /blog/ sauf /2017/07/28/fixer-ses-tarifs-freelance/ qui va renvoyer vers la page /blog/fixer-ses-tarifs-freelance/
- [x] Mettre en place les bons boutons pour l'ajout à Slack et la connexion au dashboard
    cf : installation du bot depuis le Slack Store https://api.slack.com/slack-apps#installing_apps
- [x] s'occuper de la page [Pourquoi](https://beta.gryzzly.io/www/pourquoi/)
- [x] Intégrer la page pourquoi

Les étapes à ne pas oublier avant de livrer l'API :

- [x] bloquer les requêtes `GET` vers l'API
- [x] ajouter un container pour l'API en prod

**Comment by aitva** [comment]
Pour la partie déploiement du nouveau site :

- [ ] mettre à jour le `Caddyfile` de [gryzzly-io](https://github.com/gryzzlybot/gryzzly-io)
- [ ] mettre à jour le `Caddyfile` de [gryzzlyio](https://github.com/gryzzlybot/gryzzlyio)
- [ ] mettre à jour `docker-compose.yml` de [gryzzly-io](https://github.com/gryzzlybot/gryzzly-io)

**Comment by Johnmgt** [comment]
Pour les redirections du blog tu peux me les lister @aitva ? je vais voir ce que j'en fait

**Comment by aitva** [comment]
Je n'ai que ça en redirection :

```
gryzzly.fr, www.gryzzly.fr {
    redir / https://www.gryzzly.io/{path}?{query}&from={host} 301
}

blog.gryzzly.fr {
    redir / https://www.gryzzly.io/blog/ 301
}
```
