### ISSUE TITLE
Mettre tout le domaine timer.gryzzly.io en no index

### ISSUE THREAD

**Issue by Johnmgt** [gryzzlybot/www#16]

**Comment by aitva** [comment]
Je pense que c'est bon. Ci-dessous des examples de réponse de [timer.gryzzly.io](http://timer.gryzzly.io/).

Pour [timer.gryzzly.io](http://timer.gryzzly.io/):
```bash
$ curl -I http://timer.gryzzly.io/
HTTP/1.1 200 OK
...
X-Robots-Tag: noindex, nofollow
...
```
Pour [timer.gryzzly.io/a-propos](http://timer.gryzzly.io/a-propos/):
```bash
$ curl -I http://timer.gryzzly.io/a-propos
HTTP/1.1 200 OK
...
X-Robots-Tag: noindex, nofollow
...
```

**Comment by Johnmgt** [comment]
https://www.google.com/search?q=timer%20gryzzly%20lyon&oq=timer%20gryzzly%20lyon&sourceid=chrome&from=coli

On a deux page du sous domaine qui remonte : a-propos et blog

**Comment by Johnmgt** [comment]
Hello Louis, est-ce qu'on peut fermer ce ticket ?

**Comment by aitva** [comment]
Yep, je ne vois plus timer.gryzzly.io sur Google.
