### ISSUE TITLE
Rendre le formulaire de contact home fonctionnel

### ISSUE THREAD

**Issue by Johnmgt** [gryzzlybot/www#6]

**Comment by aitva** [comment]
Le formulaire de contacte fonctionne ! 🎉

Par contre, il manque une page sur laquelle rediriger l'utilisateur après qu'il ai soumis le formulaire.

**Comment by Johnmgt** [comment]
La solution la plus simple serai d'afficher un bandeau de confirmation au dessus du form quand c'est envoyé non ?
